### PR TITLE
Made it work again

### PR DESCRIPTION
**Pull request by JCH2k**
- Disabled autoupdater (still used google code)
- Accept "premium" in window title

### CODE REVIEW

**Review by jucrouzet — APPROVED** [review]
Thank you

**Comment by jucrouzet** [comment]
@JCH2k : I'm not on a windows desktop anymore, are you interested for an ownership transfer ?

**Comment by JCH2k** [comment]
I'll first _use_ the tool for a few days before deciding to maintain it, but in general, yes, why not.

**Comment by jucrouzet** [comment]
@JCH2k : Ok, great, keep me updated.
Can you compile and upload a binary ?

**Comment by JCH2k** [comment]
It works, so I'm open to a transfer.
Created a release in my fork. The installer project format is unknown to my VS, so I only uploaded the EXE for now.

**Comment by jucrouzet** [comment]
👍 
Great news, I do the transfer !

Thanks again

**Comment by jucrouzet** [comment]
I can't do it, as you already have a project by this name (the fork)

image

Can you rename or delete the fork so I can transfer it ?

**Comment by JCH2k** [comment]
Oups, renamed it...

**Comment by jucrouzet** [comment]
Sorry, still not ok
image
Seems that you need to remove the fork ...

**Comment by JCH2k** [comment]
Another thought:
If you transfer the project, all the links to your repo will be dead. But that's also how I found the project!
Woudn't it better if you just added a note at the top of the readme.md that this is no longer maintained and people should use my fork instead?

**Comment by jucrouzet** [comment]
Was thinking that transfering ownership was doing a redirect to the new project.

Ok, doing it and archiving project

**Pull request merged**
